### ISSUE TITLE
Why Sigmoid isn't used in the LKA module?

### ISSUE THREAD

**Issue by K1nght** [Visual-Attention-Network/VAN-Classification#7]
First, thanks for the great and helpful work!
I wonder why Sigmoid isn't used in the LKA module which can be written as:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/41949112/155961602-dc056698-40d5-46e5-99e0-2c402e4040e1.png">
Since in the previous works Sigmoid is always used as the last part of the attention module like SE-block[1] or CBAM[2]:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/41949112/155962328-a5d324e2-ce68-476c-b985-1d57e21fffbe.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/41949112/155962401-cf3a2140-218d-40c5-922f-ef2a07ae1dcf.png">
Are there any ablation studies about this change? Whether the fact that Sigmoid harms the performance results in this removal.
I cannot come up with why to remove Sigmoid except slight reduction in computational cost to the best of my knowledge. I would really appreciate it if you can answer my question!

[1]:Hu J, Shen L, Sun G. Squeeze-and-excitation networks[C]//Proceedings of the IEEE conference on computer vision and pattern recognition. 2018: 7132-7141.
[2]:Woo S, Park J, Lee J Y, et al. Cbam: Convolutional block attention module[C]//Proceedings of the European conference on computer vision (ECCV). 2018: 3-19.

**Comment by MenghaoGuo** [comment]
Good advice. 

Intuitively, I think that sigmoid affects gradient propagation and computation speed. However, we have not done relevant experiments in this area yet. 
If we have time, we will do this experiment.

**Comment by YanShuang17** [comment]
@MenghaoGuo 

Hi, We used your great backbone in our internal detection dataset and found two potential problem:

(1) When we export model to Libtorch and do inference with FP16, the model output is NAN, the source is the LKA, whose output value causes the overflow problem because of no normalization op (FP32 works well...).

(2) Training is unstable, when use the same optimizer config, VAN-base works well, but VAN-tiny/small can't converge.

FYI
